apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: fastapi-dep
  name: fastapi-dep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi-dep
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fastapi-dep
    spec:
      containers:
      - image: takuyayone/fastapi-sample:1.0.0
        name: fastapi-sample
        resources: {}
        livenessProbe:
          failureThreshold: 3
          periodSeconds: 10
          initialDelaySeconds: 10
          httpGet:
            path: /
            port: 4000
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          initialDelaySeconds: 10
          httpGet:
            path: /
            port: 4000
status: {}
