apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: fastapi-nodeport
  name: fastapi-nodeport
  namespace: sandbox
spec:
  ports:
  - name: "4000"
    port: 4000
    protocol: TCP
    targetPort: 4000
    nodePort: 30400
  selector:
    app: fastapi-dep
  type: NodePort
status:
  loadBalancer: {}
