apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: fastapi-service
  name: fastapi-service
  namespace: sandbox
spec:
  ports:
  - name: 4000-4000
    port: 4000
    protocol: TCP
    targetPort: 4000
  selector:
    app: fastapi-dep
  type: ClusterIP
status:
  loadBalancer: {}
